config/routes.rb
Rails.application.routes.draw do
  get 'lab_approvals/index'

  get 'lab_approvals/show'

  get 'lab_approvals/new'

  get 'lab_approvals/edit'

  get 'lab_approvals/create'

  get 'lab_approvals/update'

  get 'lab_approvals/destroy'

  get 'users/index'

  get 'users/show'

  get 'users/new'

  get 'users/edit'

  get 'users/create'

  get 'users/update'

  get 'users/destroy'

  get 'welcome/index'

  devise_for :users
  resources :systems
  resources :networks
  resources :routers
  resources :encrypters
  resources :tests
  resources :users
  resources :labs
  resources :test_approvals
  resources :system_approvals
  resources :lab_approvals

  root to: 'welcome#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new # guest user (not logged in)

    if user.admin?

      can :manage, User

    elsif user.ia_admin?

      can :manage, TestApproval
      can :manage, SystemApproval
      can :manage, LabApproval
      can :read, Network
      can :Update, Network
      can :read, Lab
      can :read, System
      can :read, Test

    elsif user.it_admin?

      can :manage, Encrypter
      can :manage, Router
      can :manage, Network
      can :read, Lab
      can :read, System
      can :read, SystemApproval
      can :read, TestApproval
      can :read, LabApproval
      can :read, Test

    elsif user.customer?
      can :create,  LabApproval
      can :read,    LabApproval
      can :create,  SystemApproval
      can :read,    SystemApproval
      can :create,  TestApproval
      can :read,    TestApproval

      can :create,  System
      can :create,  Lab

      can :create,  Test

      # Lab Access Block
      can :update, Lab do |lab|
        lab.mgr_id == user.id
      end

      can :read, Lab do |lab|
        user.lab_id == lab.id
      end

      if user.lab_id == nil
        can :create, Lab
      end

      # User Access Block
      can :manage, User do |x|
        x.id == user.id
      end

      # System Access Block
      can :update, System do |system|
        system.lab_id == user.lab_id
      end
      can :read, System do |system|
        system.lab_id == user.lab_id
      end

      # Test Access Block
      can :update, Test do |test|
        test.system.lab_id == user.lab_id
      end
      can :read, Test do |test|
        test.system.lab_id == user.lab_id
      end

    end
  end
end

# Define abilities for the passed in user here. For example:
#
#   user ||= User.new # guest user (not logged in)
#   if user.admin?
#     can :manage, :all
#   else
#     can :read, :all
#   end
#
# The first argument to `can` is the action you are giving the user
# permission to do.
# If you pass :manage it will apply to every action. Other common actions
# here are :read, :create, :update and :destroy.
#
# The second argument is the resource the user can perform the action on.
# If you pass :all it will apply to every resource. Otherwise pass a Ruby
# class of the resource.
#
# The third argument is an optional hash of conditions to further filter the
# objects.
# For example, here the user can only update published articles.
#
#   can :update, Article, :published => true
#
# See the wiki for details:
# https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

app/models/assist.rb
class Assist < ActiveRecord::Base
end

app/models/encrypter.rb
class Encrypter < ActiveRecord::Base
  belongs_to :test
end

app/models/get_current_test.rb
class GetCurrentTest
  attr_reader :id

  def initialize(id)
    params ||= {}
    @id = id
    #@end_date = parsed_date(params[:end_date], @end_date.to_date.to_s)
  end

  def scope
    @current_date =  Date.today.to_s
    #Test.where('end_date > ? AND ? > start_date AND network_id = ?', @current_date, @current_date, @id )
    Test.where('? BETWEEN start_date AND end_date AND network_id = ?', @current_date, @id )
    #Test.where('end_date > ?', @current_date )
  end

  private

  def parsed_date(date_string, default)
    Date.parse(date_string)
  rescue ArgumentError, TypeError
    default
  end

  def parsed_id(find_id)
    find_id.to_int
  end

end

app/models/lab.rb
class Lab < ActiveRecord::Base

  has_many :users
  has_many :systems

  has_one :lab_approval, dependent: :destroy

  belongs_to :manger, foreign_key: "mgr_id", class_name: "User"

  has_attached_file :accrediation
  do_not_validate_attachment_file_type :accrediation

  has_attached_file :loa
  do_not_validate_attachment_file_type :loa

end

app/models/lab_approval.rb
class LabApproval < ActiveRecord::Base
  belongs_to :lab
end

app/models/network.rb
class Network < ActiveRecord::Base
  has_many :tests
end

app/models/router.rb
class Router < ActiveRecord::Base
  belongs_to :test
end

app/models/system.rb
class System < ActiveRecord::Base
  has_many :tests
  has_one :system_approval, dependent: :destroy

  belongs_to :lab

  has_attached_file :atoDoc
  do_not_validate_attachment_file_type :atoDoc
end

app/models/system_approval.rb
class SystemApproval < ActiveRecord::Base
  belongs_to :system
end

app/models/test.rb
class Test < ActiveRecord::Base
  has_many :encrypters
  has_many :routers
  has_one :test_approval, dependent: :destroy

  belongs_to :network
  belongs_to :system

  has_attached_file :allLabMoA
  do_not_validate_attachment_file_type :allLabMoA

  has_attached_file :testProcedures
  do_not_validate_attachment_file_type :testProcedures
end

app/models/test_approval.rb
class TestApproval < ActiveRecord::Base
  belongs_to :test
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :lab

end

app/controllers/test_approvals_controller.rb
class TestApprovalsController < ApplicationController
  before_action :set_test_approval, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /test_approvals
  # GET /test_approvals.json
  def index
    @test_approvals = TestApproval.all
  end

  # GET /test_approvals/1
  # GET /test_approvals/1.json
  def show
  end

  # GET /test_approvals/new
  def new
    @test_approval = TestApproval.new
  end

  # GET /test_approvals/1/edit
  def edit
  end

  # POST /test_approvals
  # POST /test_approvals.json
  def create
    @test_approval = TestApproval.new(test_approval_params)

    respond_to do |format|
      if @test_approval.save
        format.html { redirect_to @test_approval, notice: 'Test approval was successfully created.' }
        format.json { render :show, status: :created, location: @test_approval }
      else
        format.html { render :new }
        format.json { render json: @test_approval.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /test_approvals/1
  # PATCH/PUT /test_approvals/1.json
  def update
    @test = @test_approval.test
    respond_to do |format|
      if @test_approval.update(test_approval_params)

        #Sending E-mails
        if @test_approval.approved?
          TestMailer.test_approved(@test).deliver_now
        end

        format.html { redirect_to @test_approval, notice: 'Test approval was successfully updated.' }
        format.json { render :show, status: :ok, location: @test_approval }
      else
        format.html { render :edit }
        format.json { render json: @test_approval.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /test_approvals/1
  # DELETE /test_approvals/1.json
  def destroy
    @test_approval.destroy
    respond_to do |format|
      format.html { redirect_to test_approvals_url, notice: 'Test approval was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test_approval
      @test_approval = TestApproval.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_approval_params
      params.require(:test_approval).permit(:approved, :test_id)
      #params.fetch(:test_approval, {})
    end
end

app/helpers/encrypters_helper.rb
module EncryptersHelper
end

app/helpers/labs_helper.rb
module LabsHelper
end

app/helpers/networks_helper.rb
module NetworksHelper
end

app/helpers/routers_helper.rb
module RoutersHelper
end

app/helpers/systems_helper.rb
module SystemsHelper
end

app/helpers/test_approvals_helper.rb
module TestApprovalsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/test_approvals/_form.html.erb
<div class="row">
  <%= form_for @test_approval, html: { class: 'form-horizontal'} do |f| %>
    <% if @test_approval.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@test_approval.errors.count, "error") %> prohibited this test_approval from being saved:</h2>

        <ul>
        <% @test_approval.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="control-group">
      <%= f.label :approved, class: 'control-label' %>
      <div class="controls">
        <%= f.check_box :approved %>
      </div>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/test_approvals/edit.html.erb
<h1>
  <%= @test_approval.test.system.lab.name%>:   <%= @test_approval.test.system.name%><br>
  <%= @test_approval.test.name%>
</h1>

<%= render 'form' %>

<%= link_to 'Show', @test_approval %> |
<%= link_to 'Back', test_approvals_path %>

app/views/test_approvals/index.html.erb
<h1>Listing Tests</h1>

<div class="media">
  <div class="media-body">
    <table class="table table-hover">
      <thead>
      <tr>
        <th>Test Name</th>
        <th>Network</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Approved</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
        <% @test_approvals.each do |test_approval| %>
          <% if current_user.lab_id == test_approval.test.system.lab_id ||
              current_user.ia_admin? || current_user.it_admin? %>
            <tr>
              <td><%= test_approval.test.name %></td>
              <td><%= test_approval.test.network.classification if test_approval.test.network %></td>
              <td><%= test_approval.test.start_date %></td>
              <td><%= test_approval.test.end_date %></td>
              <td><%= test_approval.approved %></td>

              <td><%= link_to 'Show', test_approval.test, class: 'btn btn-primary' %></td>

              <% if current_user.ia_admin? %>
                <td><%= link_to 'Edit', edit_test_approval_path(test_approval), class: "btn btn-success" %></td>
              <% elsif current_user.customer? %>
                <td><%= link_to 'Edit', edit_test_path(test_approval.test), class: "btn btn-success" %></td>
                <td><%= link_to 'Destroy', test_approval.test, method: :delete, class: "btn btn-danger",
                                data: { confirm: 'Are you sure?' } %></td>
              <% end %>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<br>

<% if current_user.customer? && current_user.lab_id != nil %>
    <%= link_to 'New Test', new_test_path, class: 'btn btn-default' %>
<% end %>

app/views/test_approvals/new.html.erb
<h1>New Test Approval</h1>

<%= render 'form' %>

<%= link_to 'Back', test_approvals_path %>

app/views/test_approvals/show.html.erb
<%= link_to 'Edit', edit_test_approval_path(@test_approval) %> |
<%= link_to 'Back', test_approvals_path %>