config/routes.rb
Rails.application.routes.draw do
  get 'lab_approvals/index'

  get 'lab_approvals/show'

  get 'lab_approvals/new'

  get 'lab_approvals/edit'

  get 'lab_approvals/create'

  get 'lab_approvals/update'

  get 'lab_approvals/destroy'

  get 'users/index'

  get 'users/show'

  get 'users/new'

  get 'users/edit'

  get 'users/create'

  get 'users/update'

  get 'users/destroy'

  get 'welcome/index'

  devise_for :users
  resources :systems
  resources :networks
  resources :routers
  resources :encrypters
  resources :tests
  resources :users
  resources :labs
  resources :test_approvals
  resources :system_approvals
  resources :lab_approvals

  root to: 'welcome#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new # guest user (not logged in)

    if user.admin?

      can :manage, User

    elsif user.ia_admin?

      can :manage, TestApproval
      can :manage, SystemApproval
      can :manage, LabApproval
      can :read, Network
      can :Update, Network
      can :read, Lab
      can :read, System
      can :read, Test

    elsif user.it_admin?

      can :manage, Encrypter
      can :manage, Router
      can :manage, Network
      can :read, Lab
      can :read, System
      can :read, SystemApproval
      can :read, TestApproval
      can :read, LabApproval
      can :read, Test

    elsif user.customer?
      can :create,  LabApproval
      can :read,    LabApproval
      can :create,  SystemApproval
      can :read,    SystemApproval
      can :create,  TestApproval
      can :read,    TestApproval

      can :create,  System
      can :create,  Lab

      can :create,  Test

      # Lab Access Block
      can :update, Lab do |lab|
        lab.mgr_id == user.id
      end

      can :read, Lab do |lab|
        user.lab_id == lab.id
      end

      if user.lab_id == nil
        can :create, Lab
      end

      # User Access Block
      can :manage, User do |x|
        x.id == user.id
      end

      # System Access Block
      can :update, System do |system|
        system.lab_id == user.lab_id
      end
      can :read, System do |system|
        system.lab_id == user.lab_id
      end

      # Test Access Block
      can :update, Test do |test|
        test.system.lab_id == user.lab_id
      end
      can :read, Test do |test|
        test.system.lab_id == user.lab_id
      end

    end
  end
end

# Define abilities for the passed in user here. For example:
#
#   user ||= User.new # guest user (not logged in)
#   if user.admin?
#     can :manage, :all
#   else
#     can :read, :all
#   end
#
# The first argument to `can` is the action you are giving the user
# permission to do.
# If you pass :manage it will apply to every action. Other common actions
# here are :read, :create, :update and :destroy.
#
# The second argument is the resource the user can perform the action on.
# If you pass :all it will apply to every resource. Otherwise pass a Ruby
# class of the resource.
#
# The third argument is an optional hash of conditions to further filter the
# objects.
# For example, here the user can only update published articles.
#
#   can :update, Article, :published => true
#
# See the wiki for details:
# https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

app/models/assist.rb
class Assist < ActiveRecord::Base
end

app/models/encrypter.rb
class Encrypter < ActiveRecord::Base
  belongs_to :test
end

app/models/get_current_test.rb
class GetCurrentTest
  attr_reader :id

  def initialize(id)
    params ||= {}
    @id = id
    #@end_date = parsed_date(params[:end_date], @end_date.to_date.to_s)
  end

  def scope
    @current_date =  Date.today.to_s
    #Test.where('end_date > ? AND ? > start_date AND network_id = ?', @current_date, @current_date, @id )
    Test.where('? BETWEEN start_date AND end_date AND network_id = ?', @current_date, @id )
    #Test.where('end_date > ?', @current_date )
  end

  private

  def parsed_date(date_string, default)
    Date.parse(date_string)
  rescue ArgumentError, TypeError
    default
  end

  def parsed_id(find_id)
    find_id.to_int
  end

end

app/models/lab.rb
class Lab < ActiveRecord::Base

  has_many :users
  has_many :systems

  has_one :lab_approval, dependent: :destroy

  belongs_to :manger, foreign_key: "mgr_id", class_name: "User"

  has_attached_file :accrediation
  do_not_validate_attachment_file_type :accrediation

  has_attached_file :loa
  do_not_validate_attachment_file_type :loa

end

app/models/lab_approval.rb
class LabApproval < ActiveRecord::Base
  belongs_to :lab
end

app/models/network.rb
class Network < ActiveRecord::Base
  has_many :tests
end

app/models/router.rb
class Router < ActiveRecord::Base
  belongs_to :test
end

app/models/system.rb
class System < ActiveRecord::Base
  has_many :tests
  has_one :system_approval, dependent: :destroy

  belongs_to :lab

  has_attached_file :atoDoc
  do_not_validate_attachment_file_type :atoDoc
end

app/models/system_approval.rb
class SystemApproval < ActiveRecord::Base
  belongs_to :system
end

app/models/test.rb
class Test < ActiveRecord::Base
  has_many :encrypters
  has_many :routers
  has_one :test_approval, dependent: :destroy

  belongs_to :network
  belongs_to :system

  has_attached_file :allLabMoA
  do_not_validate_attachment_file_type :allLabMoA

  has_attached_file :testProcedures
  do_not_validate_attachment_file_type :testProcedures
end

app/models/test_approval.rb
class TestApproval < ActiveRecord::Base
  belongs_to :test
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :lab

end

app/helpers/labs_helper.rb
module LabsHelper
end

app/helpers/networks_helper.rb
module NetworksHelper
end

app/helpers/routers_helper.rb
module RoutersHelper
end

app/helpers/systems_helper.rb
module SystemsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>JOINLabwebapp</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div class="container">

      <ul class="nav nav-tabs">

        <% if current_user %>
          <% temp_s = "Login in as: " + current_user.email %>

          <li> <div class="badge right-nav" > <%= temp_s %></div> </li>

          <% if current_user.customer? %>
            <li><%= link_to "Tests", test_approvals_path %></li>
            <li><%= link_to "Systems", system_approvals_path %></li>
            <li><%= link_to "Labs", lab_approvals_path %></li>
            <li><%= link_to "Account",  users_index_path %></li>

          <% elsif current_user.admin?%>
            <li><%= link_to "Users", users_index_path %></li>

          <% elsif current_user.it_admin? %>
            <li><%= link_to "Networks", networks_path %></li>
            <li>
              <div class = 'btn-group pull-right right-nav'>
                <button type="button" class="btn btn-mini dropdown-toggle" data-toggle="dropdown">
                  <span class="caret"></span>
                  <span class="sr-onlly">Equipment</span>
                </button>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to "Routers", routers_path %></li>
                  <li><%= link_to "Encrypters", encrypters_path %></li>
                </ul>
              </div>
            </li>
            <li><%= link_to "Tests", test_approvals_path %></li>
            <li><%= link_to "Systems", system_approvals_path %></li>
            <li><%= link_to "Labs", lab_approvals_path %></li>

          <% elsif current_user.ia_admin? %>
            <li><%= link_to "Networks", networks_path %></li>
            <li><%= link_to "Tests", test_approvals_path %></li>
            <li><%= link_to "Systems", system_approvals_path %></li>
            <li><%= link_to "Labs", lab_approvals_path %></li>

          <% end %>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>

        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>

        <% end %>

      </ul>

      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">
            &times;
          </button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:error] %>
        <div class="alert alert-error">
          <button type="button" class="close" data-dismiss="alert">
            &times;
          </button>
          <%= flash[:error] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert">
          <button type="button" class="close" data-dismiss="alert">
            &times;
          </button>
          <%= flash[:alert] %>
        </div>
      <% end %>

      <%= yield %>

    </div>

  </body>

</html>